spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service
    username: identity_service
    password: change-me
  jdbc:
    template:
      fetch-size: 100
  flyway:
    enabled: true
    locations: classpath:db/migration
  main:
    banner-mode: off
logging:
  level:
    org.springframework.jdbc.core: DEBUG
